"""Local PerfPilot service.

This service is deliberately conservative about evidence: it only calls a value
"measured" when it was generated by the benchmark runner in this process.
Everything derived from a model or heuristic is marked "estimated".
"""

from __future__ import annotations

import statistics
import time
from dataclasses import asdict, dataclass
from typing import Literal

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

app = FastAPI(title="PerfPilot API", version="0.1.0", description="Local, evidence-first AI performance analysis.")
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000"],
    allow_methods=["GET", "POST"],
    allow_headers=["*"],
)


@dataclass(frozen=True)
class Evidence:
    name: str
    value: float
    unit: str
    provenance: Literal["measured", "estimated"]
    method: str


class BenchmarkRequest(BaseModel):
    iterations: int = Field(default=40, ge=5, le=400)
    workload_size: int = Field(default=4_000, ge=100, le=100_000)


class AnalyzeRequest(BaseModel):
    repository: str = Field(min_length=3, max_length=256)
    base_ref: str = "main"
    head_ref: str = "HEAD"


def deterministic_workload(size: int) -> int:
    """CPU-only workload with no optional dependencies; prevents dead-code removal."""
    accumulator = 0
    for value in range(size):
        accumulator = (accumulator * 1_103_515_245 + value + 12_345) & 0x7FFFFFFF
    return accumulator


def run_benchmark(iterations: int, workload_size: int) -> list[float]:
    # Warm the interpreter and establish a stable-ish local baseline.
    for _ in range(5):
        deterministic_workload(workload_size)
    samples: list[float] = []
    for _ in range(iterations):
        start = time.perf_counter_ns()
        deterministic_workload(workload_size)
        samples.append((time.perf_counter_ns() - start) / 1_000_000)
    return samples


@app.get("/health")
def health() -> dict[str, str]:
    return {"status": "ok", "service": "perfpilot"}


@app.post("/v1/benchmarks/run")
def benchmark(request: BenchmarkRequest) -> dict[str, object]:
    samples = run_benchmark(request.iterations, request.workload_size)
    ordered = sorted(samples)
    p95_index = min(len(ordered) - 1, round((len(ordered) - 1) * 0.95))
    median_ms = statistics.median(samples)
    p95_ms = ordered[p95_index]
    return {
        "configuration": {"iterations": request.iterations, "workload_size": request.workload_size},
        "evidence": [
            asdict(Evidence("median_latency", round(median_ms, 4), "ms", "measured", "time.perf_counter_ns")),
            asdict(Evidence("p95_latency", round(p95_ms, 4), "ms", "measured", "time.perf_counter_ns")),
            asdict(Evidence("throughput", round(1000 / median_ms, 2), "runs/s", "measured", "inverse median latency")),
        ],
        "samples_ms": [round(sample, 4) for sample in samples],
        "note": "This endpoint measures the local deterministic workload. It does not claim model inference performance.",
    }


@app.post("/v1/analyze")
def analyze(request: AnalyzeRequest) -> dict[str, object]:
    """Produce an analysis envelope without inventing repository-specific metrics.

    Repository integration belongs in the GitHub Action. Until its artifact is
    supplied, the UI can display only the local benchmark evidence below.
    """
    measured = benchmark(BenchmarkRequest(iterations=20, workload_size=4_000))
    return {
        "repository": request.repository,
        "comparison": {"base": request.base_ref, "head": request.head_ref},
        "state": "local_benchmark_complete",
        "evidence": measured["evidence"],
        "findings": [],
        "limitations": [
            "No source checkout or model artifact was provided to the local service.",
            "Repository-specific regressions require a PerfPilot GitHub Action artifact.",
        ],
    }
